jobs:
  export-secrets-repo:
    name: Export Secrets (repo)
    runs-on: windows-latest
    steps:
      - name: Export Secrets to CSV (repo)
        uses: martins-vds/export-secrets-action@v1
        env:
          SECRETS_REPO_SECRET1: ${{ secrets.SONAR_HOST_URL }}
          SECRETS_REPO_SECRET2: ${{ secrets.SONAR_TOKEN }}    
        with:
          repository: ${{ github.repository }}
          secrets-prefix: 'SONAR_'
          secrets-type: 'repo'
