on:
  schedule:
    # Runs every day At 01:00.
    - cron:  '0 1 * * *'
  pull_request:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan ZAP website
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: 'https://www.zaproxy.org/'
